Offense defense stats in db
OpenThrone/OpenThrone pull request #197
Opened 2024-08-26 22:21 UTC by uaktags

I think this is about ready:
- Added stats to the user table
- grab stats from db instead of calculating from userModel. Should increase performance and fix flickering #171 
- uses transactions to update db for rollback support incase anything goes wrong

2024-08-27 00:09 UTC, MarkTraceur requested changes
Needs an update to README to let folks know how to update the database (which we didn't need until now because nobody could run the server locally anyway)

2024-08-30 00:27 UTC, uaktags commented
Will add a blurb to readme on doing updates mid-development/game lifecycle

2024-08-30 00:44 UTC, uaktags commented
### Handling Updates from Upstream

When you pull the latest updates from the upstream repository, there may be new migrations, dependencies, or configuration changes. Follow these steps to ensure everything runs smoothly:

1. **Pull the Latest Updates:**
   ```bash
   git pull upstream main
   ```

2. **Install New Dependencies:**
    - If there are updates to `package.json`, you may need to install new dependencies:
    ```bash
    npm install
    ```

3. **Update the Database Schema:**
   - If there are new Prisma migrations, run the following command to apply them:
     ```bash
     npx prisma migrate dev
     ```
   - This command will apply the latest migrations and sync your database schema with the code.

4. **Rebuild the Project (if necessary):**
   - If there are changes in TypeScript types or other build-related changes, you may need to rebuild the project:
     ```bash
     npm run build
     ```

5. **Restart the Development Server:**
   - Ensure the server is restarted to pick up all changes:
     ```bash
     npm run bun-dev
     ```

2024-09-02 01:00 UTC, MarkTraceur approved these changes

2024-09-02 01:09 UTC, merged